#!/usr/bin/env zsh
#
# Run all dotfiles installers.
set -e

cd "$(dirname "$0")/.." || exit
DOTFILES_ROOT=$(pwd -P)
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"
cd "$DOTFILES_ROOT"

info "Find the installers and run them iteratively"
FAILED=0
for installer in "${DOTFILES_ROOT}"/**/install.sh; do
    info "Run ${installer}..."
    if LOG_DEPTH=$((${LOG_DEPTH:-0} + 1)) sh -c "$installer"; then
        success "${installer}"
    else
        warning "${installer} failed"
        FAILED=1
    fi
done
exit $FAILED
