#!/usr/bin/env zsh
#
# Run all dotfiles updaters.
set -e

cd "$(dirname "$0")/.." || exit
DOTFILES_ROOT=$(pwd -P)
# shellcheck source=tools
. "$DOTFILES_ROOT/scripts/tools"

info "Updating dotfiles. The las version will be dumped in the repo"
cd "$DOTFILES_ROOT"

info "Updating submodules"
git submodule update --remote --merge
success "Submodules updated"

info "Find the updaters and run them iteratively"
FAILED=0
for updater in "${DOTFILES_ROOT}"/**/update.sh; do
    info "Run ${updater}..."
    if LOG_DEPTH=$((${LOG_DEPTH:-0} + 1)) sh -c "$updater"; then
        success "${updater}"
    else
        warning "${updater} failed"
        FAILED=1
    fi
done
exit $FAILED
